# Generated by Django 5.2.7 on 2025-10-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_mealtype_remove_mealplan_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='meal_types_included',
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['membership_fee']},
        ),
        migrations.AlterModelOptions(
            name='vendormenuitem',
            options={'ordering': ['subscription_plan', 'meal_type', 'name']},
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='plan',
            new_name='subscription_plan',
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='total_amount_paid',
        ),
        migrations.RemoveField(
            model_name='vendormenuitem',
            name='is_available_globally',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='dailyorder',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time membership fee', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vendormenuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendormenuitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendormenuitem',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Which subscription plan this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='available_items',
            field=models.ManyToManyField(to='food_delivery.vendormenuitem'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('prepared', 'Prepared'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='resident_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='user_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.usersubscription'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(help_text='Duration of the plan in days (e.g., 30 for monthly)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendormenuitem',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('vendor', 'subscription_plan', 'menu_date', 'meal_type')},
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(blank=True, default='basic', null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.subscriptionplan')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('vendor', 'subscription_plan')},
            },
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
