# Generated by Django 5.2.7 on 2025-10-31 14:38

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0004_remove_subscriptionplan_meal_types_included_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendormenuitem',
            options={},
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_plan',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='dailyorder',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='membership_fee',
        ),
        migrations.RemoveField(
            model_name='vendormenuitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendormenuitem',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='vendormenuitem',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='vendormenuitem',
            name='is_available_globally',
            field=models.BooleanField(default=True, help_text='Is this item generally available from the vendor?'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='available_items',
            field=models.ManyToManyField(help_text='Items available on this menu', to='food_delivery.vendormenuitem'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_daily_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('prepared', 'Prepared'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders_from_subscription', to='food_delivery.usersubscription'),
        ),
        migrations.AlterField(
            model_name='dailyorderitem',
            name='price_at_order_time',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(help_text='Duration of the plan in days (e.g., 30 for a monthly plan)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendormenuitem',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_delivery.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='meal_types_included',
            field=models.ManyToManyField(help_text='Meal types covered by this plan', to='food_delivery.mealtype'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.mealtype'),
        ),
        migrations.AlterField(
            model_name='dailyorder',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.mealtype'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('vendor', 'menu_date', 'meal_type')},
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dailymenu',
            name='subscription_plan',
        ),
    ]
