# Generated by Django 5.2.7 on 2025-11-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0005_mealtype_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormenuitem',
            name='subscription_plans',
            field=models.ManyToManyField(help_text='Which subscription plans is this item available for?', related_name='menu_items', to='food_delivery.subscriptionplan'),
        ),
    ]
