# Generated by Django 5.1.5 on 2026-01-11 05:02

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0006_vendormenuitem_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been approved by an admin or warden.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('vendor', 'Vendor'), ('delivery_agent', 'Delivery Agent'), ('warden', 'Warden')], default='resident', max_length=20),
        ),
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('prepared', 'Prepared'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('assigned_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special instructions for the bulk order')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'delivery_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bulk_orders', to=settings.AUTH_USER_MODEL)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.mealtype')),
                ('warden', models.ForeignKey(limit_choices_to={'user_type': 'warden'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='BulkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_delivery.bulkorder')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.vendormenuitem')),
            ],
            options={
                'unique_together': {('bulk_order', 'menu_item')},
            },
        ),
    ]
