# Generated by Django 5.2.10 on 2026-01-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0007_customuser_is_approved_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='warden',
            field=models.ForeignKey(blank=True, help_text='The warden responsible for this resident.', limit_choices_to={'user_type': 'warden'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
