# Generated by Django 5.1.5 on 2026-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0008_customuser_warden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('prepared', 'Prepared'), ('out_for_delivery', 'Out for Delivery'), ('reached_location', 'Reached Location'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
